<?php

return [
    'body' => 'bg-gray-50 text-gray-800',
    'nav' => 'bg-white shadow-md',
    'navLink' => 'text-gray-600 hover:text-gray-900',
    'header' => 'bg-white shadow',
    'headerTitle' => 'text-3xl font-bold text-gray-900',
    'container' => 'bg-white shadow-sm rounded-lg',
    'title' => 'text-2xl font-bold text-gray-900',
    'content' => 'prose prose-gray max-w-none',
    'tag' => 'bg-gray-100 text-gray-700 hover:bg-gray-200',
    'link' => 'text-blue-600 hover:text-blue-800',
    'date' => 'text-gray-500',
    'views' => 'text-gray-500',
    'pagination' => 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50',
    'paginationActive' => 'bg-blue-50 border-blue-500 text-blue-600',
    'code' => 'bg-gray-100 text-gray-700',
    'pre' => 'bg-gray-100 text-gray-700',
    'table' => 'bg-white',
    'thead' => 'bg-gray-100 text-gray-700',
    'th' => 'bg-gray-100 text-gray-700',
    'td' => 'bg-gray-100 text-gray-700',
    'blockquote' => 'bg-gray-100 text-gray-700',
];
